/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prycalculadorab;

/**
 *
 * @author USUARIO
 */
public class WinCalculadora extends javax.swing.JFrame {
    String _memoria1;
    String _memoria2;
    String _signo;

    public WinCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public static String calculadora (String _memoria1, String _memoria2, String _signo){
        Double _resultado=0.0;
        String _respuesta;
        
        if (_signo.equals("-")){
            _resultado=Double.parseDouble(_memoria1)-Double.parseDouble(_memoria2);
        }
        if (_signo.equals("+")){
            _resultado=Double.parseDouble(_memoria1)+Double.parseDouble(_memoria2);
        }
        if (_signo.equals("*")){
            _resultado=Double.parseDouble(_memoria1)*Double.parseDouble(_memoria2);
        }
        if (_signo.equals("/")){
            _resultado=Double.parseDouble(_memoria1)/Double.parseDouble(_memoria2);
        }
        _respuesta=_resultado.toString();
        return _respuesta;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtPantalla = new javax.swing.JTextField();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        BtnSumar = new javax.swing.JButton();
        BtnBorrarT = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnPor = new javax.swing.JButton();
        BtnInversa = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnPunto = new javax.swing.JButton();
        BtnDividir = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA BASICA");

        TxtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        Btn1.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn1.setForeground(new java.awt.Color(153, 0, 153));
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn2.setForeground(new java.awt.Color(153, 0, 153));
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn3.setForeground(new java.awt.Color(153, 0, 153));
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        BtnRestar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnRestar.setForeground(new java.awt.Color(153, 0, 153));
        BtnRestar.setText("-");
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        Btn4.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn4.setForeground(new java.awt.Color(153, 0, 153));
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        BtnBorrar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnBorrar.setForeground(new java.awt.Color(153, 0, 153));
        BtnBorrar.setText("C");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        Btn5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn5.setForeground(new java.awt.Color(153, 0, 153));
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn6.setForeground(new java.awt.Color(153, 0, 153));
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        BtnSumar.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnSumar.setForeground(new java.awt.Color(153, 0, 153));
        BtnSumar.setText("+");
        BtnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumarActionPerformed(evt);
            }
        });

        BtnBorrarT.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnBorrarT.setForeground(new java.awt.Color(153, 0, 153));
        BtnBorrarT.setText("CE");
        BtnBorrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarTActionPerformed(evt);
            }
        });

        Btn7.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn7.setForeground(new java.awt.Color(153, 0, 153));
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn8.setForeground(new java.awt.Color(153, 0, 153));
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn9.setForeground(new java.awt.Color(153, 0, 153));
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        BtnPor.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnPor.setForeground(new java.awt.Color(153, 0, 153));
        BtnPor.setText("*");
        BtnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPorActionPerformed(evt);
            }
        });

        BtnInversa.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnInversa.setForeground(new java.awt.Color(153, 0, 153));
        BtnInversa.setText("1/x");
        BtnInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInversaActionPerformed(evt);
            }
        });

        Btn0.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        Btn0.setForeground(new java.awt.Color(153, 0, 153));
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        BtnPunto.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnPunto.setForeground(new java.awt.Color(153, 0, 153));
        BtnPunto.setText(".");

        BtnDividir.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnDividir.setForeground(new java.awt.Color(153, 0, 153));
        BtnDividir.setText("/");
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnIgual.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        BtnIgual.setForeground(new java.awt.Color(153, 0, 153));
        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtPantalla)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn0)
                        .addGap(75, 75, 75)
                        .addComponent(BtnPunto)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDividir)
                        .addGap(18, 18, 18)
                        .addComponent(BtnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn7)
                        .addGap(18, 18, 18)
                        .addComponent(Btn8)
                        .addGap(18, 18, 18)
                        .addComponent(Btn9)
                        .addGap(18, 18, 18)
                        .addComponent(BtnPor)
                        .addGap(18, 18, 18)
                        .addComponent(BtnInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn1)
                                .addGap(18, 18, 18)
                                .addComponent(Btn2)
                                .addGap(18, 18, 18)
                                .addComponent(Btn3)
                                .addGap(18, 18, 18)
                                .addComponent(BtnRestar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn4)
                                .addGap(18, 18, 18)
                                .addComponent(Btn5)
                                .addGap(18, 18, 18)
                                .addComponent(Btn6)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSumar)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnBorrarT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnBorrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BtnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"1");
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"2");
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"3");
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"4");
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"5");
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"6");
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"7");
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"8");
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        TxtPantalla.setText(TxtPantalla.getText()+"9");
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        String _cadena;
        _cadena=TxtPantalla.getText();
        
        if (_cadena.length()<=0){
            TxtPantalla.setText("0.");
        }
        else {
            if (!existepunto(TxtPantalla.getText())){
                TxtPantalla.setText(TxtPantalla.getText()+".");
                TxtPantalla.setText(_cadena);
            }
        }
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        String cadena;
        cadena=TxtPantalla.getText();
        if (cadena.length()>0){
            cadena=cadena.substring(0,cadena.length()-1);
        }
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnBorrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarTActionPerformed
        TxtPantalla.setText("");
    }//GEN-LAST:event_BtnBorrarTActionPerformed

    private void BtnInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInversaActionPerformed
        
        String _cadena;
        Double num;
        _cadena=TxtPantalla.getText();
        if (_cadena.length()>0){
            num=1/(Double.parseDouble(_cadena));
            TxtPantalla.setText(num.toString());
        }
    }//GEN-LAST:event_BtnInversaActionPerformed

    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        if (!TxtPantalla.getText().equals(""));
        _memoria1=TxtPantalla.getText();
        _signo="-";
        TxtPantalla.setText("");
                
    }//GEN-LAST:event_BtnRestarActionPerformed

    private void BtnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumarActionPerformed
         if (!TxtPantalla.getText().equals(""));
        _memoria1=TxtPantalla.getText();
        _signo="+";
        TxtPantalla.setText("");
    }//GEN-LAST:event_BtnSumarActionPerformed

    private void BtnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPorActionPerformed
         if (!TxtPantalla.getText().equals(""));
        _memoria1=TxtPantalla.getText();
        _signo="*";
        TxtPantalla.setText("");
    }//GEN-LAST:event_BtnPorActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
         if (!TxtPantalla.getText().equals(""));
        _memoria1=TxtPantalla.getText();
        _signo="/";
        TxtPantalla.setText("");
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        String _resultado;
        _memoria2=TxtPantalla.getText();
        
        if (!_memoria2.equals("")){
            _resultado=calculadora(_memoria1,_memoria2,_signo);
            TxtPantalla.setText(_resultado);
        }
    }//GEN-LAST:event_BtnIgualActionPerformed
public static boolean existepunto(String cadena){
    boolean resultado;
    resultado=false;
    
    for (int i = 0; i < cadena.length(); i++) {
        if (cadena.substring(i, i++).equals(".")){
            resultado=true;
            break;
        }
    }return resultado;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBorrarT;
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnInversa;
    private javax.swing.JButton BtnPor;
    private javax.swing.JButton BtnPunto;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSumar;
    private javax.swing.JTextField TxtPantalla;
    // End of variables declaration//GEN-END:variables
}
